name: "CS 16 Spring 2019, Nichols"
github_url: https://github.com/ucsb-cs16-s19-nichols/ucsb-cs16-s19-nichols.github.io


instances:      
  -
    instructor: Nichols
    site_url: "https://ucsb-cs16-s19-nichols.github.io"    
    github_org:
       name: ucsb-cs16-s19-nichols
       url: https://github.com/ucsb-cs16-s19-nichols
    piazza_url:  https://piazza.com/ucsb/spring2019/cs16nichols/home
    gradescope_url: https://www.gradescope.com/courses/45413



on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048

start_week: 1
start_date: 2019-03-31 00:00:00.00-8:00
num_weeks: 10
extra_exam_week: true

instructor_url: https://ucsb-cs16.github.io/instructor

cal_dates: >
  [
  {"label":"First day of classes", "date":"2019-04-01" },
  {"label":"Drop Deadline","date":"2019-04-26" },
  {"label":"Univ. Holiday", "date":"2019-05-27" },
  {"label":"Last day of classes", "date":"2019-06-07" },						
  ]

future: false

course: "CS16"
legacy_wiki_name: 16wiki
legacy_wiki_url: "https://foo.cs.ucsb.edu/16wiki"
qtr: "S19"
quarter: "Spring 2019"

markdown: kramdown
kramdown: 
  parse_block_html: true


exclude:
   - vendor

timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  -
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
